### ISSUE TITLE
error code in function find_boundary_segment(...)  line #112   

### ISSUE THREAD

**Issue by Hanqer** [yuzlee/warping_resize#1]
if (from.x == to.x) { // vert
            if (from.x <= to.x) {
                delta = Point(0, 1);
            } else {
                delta = Point(0, -1);
            }
        } 

Dose from.x <= to.x should be from.y <= to.y ?

**Comment by yuzlee** [comment]
@Hanqer Yes, you are right...I had never noticed the bug because I always use a positive `delta`. The bug has been fixed. Thank you!
